### ISSUE TITLE
Non AWS Elasticsearch service

### ISSUE THREAD

**Issue by ochart2** [vladhoncharenko/aws-dynamodb-to-elasticsearch#2]
Is it possible to do the same for a self hosted ElasticSearch cluster?
I imagine that access would need to be granted to execute against the hosted ES api?

**Comment by vladhoncharenko** [comment]
@ochart2 Yes, it's possible, but you would need to modify scripts and policies(if you use AWS) to use your self-hosted ES cluster.

**Comment by ochart2** [comment]
do you know what those scripts would look like? there's just no resources on this..

ps yes hosting elastic cluster on ec2 instances

**Comment by vladhoncharenko** [comment]
@ochart2 Did you try to run scripts from this repo as is? I think if you use AWS they would work. Information how to run scripts you can find [here](https://medium.com/@vladyslavhoncharenko/how-to-index-new-and-existing-amazon-dynamodb-content-with-amazon-elasticsearch-service-30c1bbc91365).

**Comment by ochart2** [comment]
Yip, I first set up the environment using AWS ES services, and that worked fine.
Of course with a EC2 ES cluster, the script "Lambda-to-Amazon-ES" becomes redundant as we can't reference an "arn" anymore.  I imagine that i now need to change this policy to allow access "es:ESHttpPost" or something similar to a different URL, as I can't reference an AWS resource anymore.
Another change is that the lambda python script would now need to point to some ES server (ip:9200) or proxy, instead of the AWS ES location.

**Comment by vladhoncharenko** [comment]
If you want to open access to your ES cluster for everyone you could add a policy to the EC2 with something like "Action": "ec2:*" and "Resource": "*" and without conditions(you can specify actions or resources instead of wildcards).
If you want to make access only to your client(s) you should:
1) Add policy to the EC2 instance with access for the specified AWS user only.
2) Sign all your requests to EC2 with secret/access keys of the user from step 1.

**Comment by ochart2** [comment]
Found the problem, the lambda script had https hardcoded into it...
So changed that to http and just dropped the Lambda-to-Amazon-ES permission.

Thanks for the help!
